#!/usr/bin/env python3
"""Generate src/ituzones.h from the RSGB ITU zones list PDF.

Source: https://www.rsgbshop.org/acatalog/PDF/Worked_ITU_Zones_ITU_Zones_List.pdf
Re-run when the list changes:
    python3 tools/gen_ituzones.py path/to/ITU_Zones_List.pdf

ITU zones (unlike CQ zones) have no descriptive names -- just a number and a
prefix/region definition. The numbering is not contiguous (this list has 1-75,
78 and 90). Emits every zone present, verbatim.
"""
import sys, re

def parse(path):
    from pypdf import PdfReader
    t = ''.join((p.extract_text() or '') for p in PdfReader(path).pages)
    i = t.find('List of ITU zones')
    if i >= 0: t = t[i:]
    t = re.sub(r'[ \t]+', ' ', t)
    zones = {}
    # Accept "N." and also "N " (the source has one entry, 78, without the period).
    # A zone starts at a number followed by '.' or a space, then an uppercase letter
    # or a word like "Antarctica"/"CE0". Capture lazily to the next such marker.
    for m in re.finditer(r'(?:^|\n|\s)(\d{1,2})[.\s]\s*([A-Z0-9].*?)(?=\s\d{1,2}[.\s]\s*[A-Z0-9]|\Z)', t, re.S):
        n = int(m.group(1)); txt = re.sub(r'\s+', ' ', m.group(2)).strip()
        if n < 1 or n > 90: continue
        if n not in zones and len(txt) > 1:
            zones[n] = txt
    return zones

def esc(s): return s.replace('\\', '\\\\').replace('"', '\\"')

def emit(zones, out):
    L = ['// Auto-generated by tools/gen_ituzones.py from the RSGB ITU zones list.',
         '// Source: https://www.rsgbshop.org/acatalog/PDF/Worked_ITU_Zones_ITU_Zones_List.pdf',
         '// Do not edit by hand -- re-run the generator when the list changes.',
         '#pragma once', '',
         'struct ItuZone { uint8_t n; const char* detail; };',
         'static const ItuZone ITU_ZONES[] = {']
    for n in sorted(zones):
        L.append('  {%d, "%s"},' % (n, esc(zones[n])))
    L.append('};')
    L.append('static const int ITU_ZONES_N = %d;' % len(zones))
    open(out, 'w').write('\n'.join(L) + '\n')
    return len(zones)

if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else 'ITU_Zones_List.pdf'
    out = sys.argv[2] if len(sys.argv) > 2 else 'src/ituzones.h'
    z = parse(src)
    n = emit(z, out)
    print('wrote %s: %d ITU zones (numbers: %s)' % (out, n, ','.join(str(k) for k in sorted(z))))
