#!/usr/bin/env python3
"""Generate src/cqzones.h from the CQ WAZ zone list (cq_waz_list.htm).

Source: https://cqww.com/cq_waz_list.htm
Re-run when CQ updates the definitions:
    python3 tools/gen_cqzones.py path/to/cq_waz_list.htm

Emits all 40 CQ (WAZ) zones: short name plus the full prefix/region detail text,
verbatim. Used by the CQ-zone reference tool and linked from the DXCC detail card.
"""
import sys, re, html

def parse(path):
    t = open(path, encoding='utf-8', errors='replace').read()
    txt = re.sub(r'<[^>]+>', ' ', t); txt = html.unescape(txt); txt = re.sub(r'[ \t]+', ' ', txt)
    zones = {}
    for m in re.finditer(r'Zone\s+(\d{1,2})\s*\.\s*([^:]+?)\s*:\s*(.*?)(?=Zone\s+\d{1,2}\s*\.|\Z)', txt, re.S):
        n = int(m.group(1)); name = m.group(2).strip()
        detail = re.sub(r'\s+', ' ', m.group(3)).strip().rstrip('. ').strip()
        zones[n] = (name, detail)
    return zones

def esc(s): return s.replace('\\', '\\\\').replace('"', '\\"')

def emit(zones, out):
    L = ['// Auto-generated by tools/gen_cqzones.py from the CQ WAZ zone list.',
         '// Source: https://cqww.com/cq_waz_list.htm',
         '// Do not edit by hand -- re-run the generator when CQ updates the list.',
         '#pragma once', '',
         'struct CqZone { uint8_t n; const char* name; const char* detail; };',
         'static const CqZone CQ_ZONES[] = {']
    for n in range(1, 41):
        if n not in zones: continue
        name, detail = zones[n]
        L.append('  {%d, "%s", "%s"},' % (n, esc(name), esc(detail)))
    L.append('};')
    L.append('static const int CQ_ZONES_N = %d;' % len([n for n in range(1, 41) if n in zones]))
    open(out, 'w').write('\n'.join(L) + '\n')
    return len(zones)

if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else 'cq_waz_list.htm'
    out = sys.argv[2] if len(sys.argv) > 2 else 'src/cqzones.h'
    z = parse(src)
    n = emit(z, out)
    print('wrote %s: %d CQ zones' % (out, n))
