#!/usr/bin/env python3
"""Generate src/dxcc_lookup.h from the ARRL DXCC list (Current_Deleted.txt).

Source: https://www.arrl.org/files/file/DXCC/Current_Deleted.txt
The ARRL list changes about once a year; re-run to regenerate:
    python3 tools/gen_dxcc_lookup.py path/to/Current_Deleted.txt

Emits a compact C++ table (src/dxcc_lookup.h): every entity's prefix, name,
continent, ITU/CQ zones (verbatim short strings, so multi-zone like "06-08" and
note-referenced "(E)" round-trip), entity code, deleted flag, third-party flag,
and its footnote numbers. Footnotes are namespaced by section because the Current
and Deleted lists both number their notes from 2 -- the same number means
different things in each, so they are stored separately (deleted flag on the note).
"""
import sys, re

def parse(path):
    lines = [l.rstrip('\r') for l in open(path, encoding='utf-8', errors='replace').read().split('\n')]
    current, deleted = [], []
    notes = []                       # list of (number, deleted_flag, text)
    section = None
    row_rx = re.compile(r'^\s+(\S+)\s+(.*?)\s+([A-Z]{2}(?:,[A-Z]{2})*)\s+(\S+)\s+(\S+)\s+(\d{3})\s*$')
    note_rx = re.compile(r'^\s+(\d+)\s{2,}(\S.*)$')   # '<num>  <text>' (text may start with '(' or not)
    for ln in lines:
        s = ln.strip()
        if s == 'CURRENT ENTITIES': section = 'cur'; continue
        if s == 'DELETED ENTITIES': section = 'del'; continue
        if section is None: continue
        mn = note_rx.match(ln)
        if mn and not re.search(r'\s\d{3}\s*$', ln):
            notes.append((int(mn.group(1)), section == 'del', mn.group(2).strip())); continue
        if not re.search(r'\s\d{3}\s*$', ln): continue
        if 'Entity' in ln and 'Code' in ln: continue
        m = row_rx.match(ln)
        if not m: continue
        prefix, name, cont, itu, cq, code = m.groups()
        refs = [int(x) for x in re.findall(r'\((\d+)\)', prefix)]   # note numbers in parens
        base_prefix = re.sub(r'\(\d+\)', '', prefix)
        third_party = name.endswith('#') or base_prefix.endswith('#')
        base_prefix = base_prefix.rstrip('#').strip().rstrip(',').strip()
        name = name.rstrip('#').strip()
        rec = dict(prefix=base_prefix, name=name, cont=cont, itu=itu, cq=cq,
                   code=code, refs=refs, tp=third_party)
        (current if section == 'cur' else deleted).append(rec)
    return current, deleted, notes

def esc(s): return s.replace('\\', '\\\\').replace('"', '\\"')

def emit(current, deleted, notes, out):
    # assign each (number,section) note a flat index for compact per-entity refs
    note_index = {}
    for i, (n, dl, _t) in enumerate(notes): note_index[(n, dl)] = i

    def refs_literal(r, deleted_flag):
        idxs = [note_index[(n, deleted_flag)] for n in r['refs'] if (n, deleted_flag) in note_index]
        return idxs

    L = ['// Auto-generated by tools/gen_dxcc_lookup.py from the ARRL DXCC list.',
         '// Source: https://www.arrl.org/files/file/DXCC/Current_Deleted.txt',
         '// Do not edit by hand -- re-run the generator when ARRL updates the list.',
         '#pragma once', '',
         'struct DxccLk {',
         '  int16_t     code;       // ARRL entity code',
         '  const char* prefix;     // primary prefix(es)',
         '  const char* name;       // entity name',
         '  const char* cont;       // continent(s)',
         '  const char* itu;        // ITU zone(s), verbatim',
         '  const char* cq;         // CQ zone(s), verbatim',
         '  uint8_t     thirdParty; // 1 = "#", US third-party traffic OK',
         '  uint8_t     deleted;    // 1 = deleted entity',
         '  int16_t     note1;      // footnote index into DXCC_NOTES, or -1',
         '  int16_t     note2;      // second footnote index, or -1',
         '};', '',
         'static const DxccLk DXCC_LK[] = {']
    def row(r, dl):
        idxs = refs_literal(r, dl)
        n1 = idxs[0] if len(idxs) > 0 else -1
        n2 = idxs[1] if len(idxs) > 1 else -1
        return ('  {%d, "%s", "%s", "%s", "%s", "%s", %d, %d, %d, %d},'
                % (int(r['code']), esc(r['prefix']), esc(r['name']), r['cont'],
                   esc(r['itu']), esc(r['cq']), 1 if r['tp'] else 0, 1 if dl else 0, n1, n2))
    for r in current: L.append(row(r, False))
    for r in deleted: L.append(row(r, True))
    L.append('};')
    L.append('static const int DXCC_LK_N = %d;' % (len(current) + len(deleted)))
    L.append('static const int DXCC_LK_CURRENT = %d;' % len(current))
    L.append('')
    L.append('static const char* const DXCC_NOTES[] = {')
    for (n, dl, t) in notes: L.append('  "%s",' % esc(t))
    L.append('};')
    L.append('static const int DXCC_NOTES_N = %d;' % len(notes))
    open(out, 'w').write('\n'.join(L) + '\n')
    return len(current), len(deleted), len(notes)

if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else 'Current_Deleted.txt'
    out = sys.argv[2] if len(sys.argv) > 2 else 'src/dxcc_lookup.h'
    cur, dele, notes = parse(src)
    nc, nd, nn = emit(cur, dele, notes, out)
    print('wrote %s: %d current + %d deleted, %d footnotes' % (out, nc, nd, nn))
