#!/usr/bin/env python3
# Regenerates src/stars.h from d3-celestial's stars.6.json / constellations.lines.json
# / starnames.json (BSD-3, https://github.com/ofrohn/d3-celestial ; BSC5/HYG data).
# Stars to mag <= 4.6 sorted brightest-first; constellation polylines as packed
# vertex runs; proper names for the brightest stars. ~9 KB of flash rodata total.
import json, sys, os
d = os.path.dirname(os.path.abspath(__file__))
S = json.load(open(sys.argv[1])); C = json.load(open(sys.argv[2])); N = json.load(open(sys.argv[3]))
stars = []
for f in S['features']:
    m = f['properties'].get('mag', 99)
    if m > 4.6: continue
    ra, dec = f['geometry']['coordinates']
    if ra < 0: ra += 360.0
    nm = N.get(str(f['id']), {}).get('name', '')
    stars.append((m, int(round(ra*100)) % 36000, int(round(dec*100)), nm))
stars.sort(key=lambda s: s[0])
names = [(i, s[3]) for i, s in enumerate(stars) if s[3] and s[0] <= 1.6][:16]
runs, vra, vdec = [], [], []
for f in C['features']:
    for seg in f['geometry']['coordinates']:
        runs.append(len(seg))
        for ra, dec in seg:
            if ra < 0: ra += 360.0
            vra.append(int(round(ra*100)) % 36000); vdec.append(int(round(dec*100)))
def arr(t, name, vals):
    return "static const %s %s[] = {\n  %s\n};\n" % (t, name,
        ",".join(str(v) for v in vals))
out = "// GENERATED by tools/make_star_tables.py -- do not edit by hand.\n"
out += "// Data: d3-celestial (BSD-3, ofrohn/d3-celestial; BSC5/HYG). RA/dec in 0.01 deg.\n"
out += "// Stars sorted brightest-first (mag encoded as (mag+2)*10 in a uint8).\n"
out += "#pragma once\n#include <stdint.h>\n"
out += "static const int STAR_N = %d;\n" % len(stars)
out += arr("uint16_t","STAR_RA",[s[1] for s in stars])
out += arr("int16_t","STAR_DEC",[s[2] for s in stars])
out += arr("uint8_t","STAR_MAG",[max(0,min(255,int(round((s[0]+2)*10)))) for s in stars])
out += "static const int CLIN_RUNS_N = %d;\n" % len(runs)
out += arr("uint8_t","CLIN_RUN",runs)
out += arr("uint16_t","CLIN_RA",vra)
out += arr("int16_t","CLIN_DEC",vdec)
out += "static const int STAR_NAME_N = %d;\n" % len(names)
out += "static const uint16_t STAR_NAME_IDX[] = { %s };\n" % ",".join(str(i) for i,_ in names)
out += "static const char* const STAR_NAME[] = { %s };\n" % ",".join('"%s"' % n for _,n in names)
open(os.path.join(d,"..","src","stars.h"),"w").write(out)
print("stars:",len(stars),"runs:",len(runs),"verts:",len(vra),"names:",[n for _,n in names])
