#pragma once
// ===========================================================================
//  irbeacon.h  -  silent IR pass-alert beacon (built-in IR LED, GPIO 44)
// ===========================================================================
//
//  Mirrors CardSat's audible pass alerts onto the Cardputer's built-in IR LED:
//  each alert event (T-60/T-30/T-10/AOS/TCA/LOS) emits a DISTINCT number of
//  38 kHz IR bursts. The point is to give users a machine-readable trigger --
//  point any standard IR receiver/demodulator (e.g. a TSOP38238) at the
//  Cardputer, count the bursts, and drive whatever you like (relay, PTT, lights,
//  a logger). CardSat just transmits the counts; the receiving side is yours.
//
//  Non-blocking by design: flash(n) queues a burst group and service() (called
//  every loop tick) advances one carrier-on / carrier-off step at a time, so the
//  Doppler loop, rotator, and web services keep running while it flashes. The
//  38 kHz carrier is generated by LEDC hardware PWM gated on/off -- no library
//  dependency and no busy-waiting.
//
//  Disabled by default (cfg.irBeacon); enable in Settings. Uses GPIO 44 only.
//
//  *** Host-verified only as of v0.9.23: the carrier timing and state machine are
//  checked off-device; the actual IR output and a receiver decoding it want
//  confirmation on hardware. ***
// ===========================================================================
#include <Arduino.h>

class IrBeacon {
public:
  void begin();                  // configure LEDC on the IR pin (carrier idle off)
  bool ready() const { return _ok; }
  void flash(uint8_t count);     // queue a group of `count` 38 kHz bursts
  void service();                // advance the flasher one step; call every loop
  bool busy() const { return _state != IDLE; }

private:
  enum State { IDLE, ON, GAP };
  bool     _ok      = false;
  State    _state   = IDLE;
  uint8_t  _left    = 0;         // bursts remaining in the current group
  uint32_t _stepMs  = 0;         // when the current ON/GAP step ends
  void carrier(bool on);         // gate the 38 kHz carrier
};
